### ISSUE TITLE
Font with best support for atomic chillu and single compound letters

### ISSUE THREAD

**Issue by Shreeshrii** [smc/fonts#12]
Hi, 

Please let me know which malayalam font has the best support for atomic chillu and single compound letters and where I can download the latest ttf files for it.

I am want it to use for tranliteration of sanskrit texts in malayalam. Please see http://sanskritdocuments.org/all_iscii/test.htm?lang=ml for a test page. 

Thanks.
Shree

**Comment by Shreeshrii** [comment]
Hi,

Do the ttf files from http://download.savannah.gnu.org/releases/smc/fonts/malayalam-fonts-6.1/ have the support for atomic chillus - meaning would they render the chillu glyph when the separate codepoints are given ...

**Comment by santhoshtr** [comment]
Yes. They support both types of chillus.
