### ISSUE TITLE
Fonts looks smaller after installing SMC fonts

### ISSUE THREAD

**Issue by shyamjos** [smc/fonts#15]
Malayalam font became smaller after installing smc fonts in fedora 24 (when using facebook and wikipedia)

**Comment by jishnu7** [comment]
This may not be the ideal solution. but I use following workaround. 

https://github.com/jishnu7/dotfiles/blob/master/etc/fonts/conf.avail/52-malayalam.conf

**Comment by shyamjos** [comment]
Not working for me , changing the "minimum font size" option in google chrome fix the issue but it makes overall UI ugly , So i am sticking with lohith font for now 
http://i.imgur.com/KXU6eMM.png

**Comment by jishnu7** [comment]
did you run fc-cache after adding the file?

`[sudo] fc-cache -fv`

**Comment by shyamjos** [comment]
Yes

**Comment by rajeeshknambiar** [comment]
Looking at the screenshot:
1. Did you install gnu-free-serif-fonts or gnu-free-sans-fonts? Please uninstall it.
2. Second one looks like Meera, but some glyphs look totally weird.
3. If you want slightly bigger font, install smc-anjalioldlipi-fonts and uninstall smc-meera-fonts.

**Comment by shyamjos** [comment]
Removed  gnu-free-fonts
Installed anjalioldlipi but Lohit seems more readable for me http://i.imgur.com/IvOxakZ.png
