### ISSUE TITLE
notdef contains Ligature2 in Kalyani.sfd

### ISSUE THREAD

**Issue by primejyothi** [smc/fonts#5]
The .notdef glyph  in Kalyani.sfd file contains "Ligature2: "'half' Half Forms in Malay+AQEA-lam lookup 1 subtable" uni0D2C uni0D4D"

The font is not broken per se. The anomaly was noticed while testing a utility to rename the glyphs based on the ligatures associated with the glyphs. Since the .notdef had ligatures, it was renamed to something else and the text rendered with modified font was different compared to original.

**Comment by santhoshtr** [comment]
Thanks for reporting.
